name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  REPOSITORY: gonzalovazquez/${{ repository }}
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn' # Enable yarn cache

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build:all

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: ${{ secrets.AWS_ACCOUNT_ID }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
          registry-type: public

    - name: Build, tag, and push image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: i2c1m6e4
      run: |
        # Build your Docker image.
        docker build . -f Dockerfile -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

        # Push this image to Amazon ECR.
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest

    - name: Verify pushed images
      run: |
        aws ecr-public describe-images --repository-name $REPOSITORY --image-ids imageTag=$IMAGE_TAG
